name: Telegram Bot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Checkout кода из репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # Шаг 2: Установка Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Шаг 3: Установка зависимостей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytelegrambotapi moviepy flake8

    # Шаг 4: Линтинг (Проверка кода)
    - name: Run linter (flake8)
      run: |
        flake8 bot.py

    # Шаг 5: Тестирование (при необходимости можно добавить тесты)
    - name: Run bot tests (если тесты добавлены)
      run: |
        echo "No tests implemented yet"  # Здесь можно запустить тесты, если они есть
